# DeluxeMenus 1.13.3-DEV-86 main configuration file
# 
# A full wiki on how to use this plugin can be found at:
# https://github.com/help-chat/DeluxeMenus/wiki

debug: false
check_updates: false
gui_menus:
  caidan_index:
    file: caidan_index.yml
  caidan_setting:
    file: caidan_setting.yml
  index:
    file: index.yml
