requirements:
  unknown: "&cNot Allowed"
  property_requirement: "&r&cRequires: &6$property &cof &4$value"
  property_max: "&r&cYour &6$property &cis maxed out"
  property_min: "&r&cYour &6$property &cmust be greater than &4$value"
  no_wand: "&cYou must be holding a wand!"
  no_template: "&cYou may not learn with that $wand&c."
  no_path: "&cYou may not learn here."
  no_class: "&cYou must be a $class"
  no_required_path: "&cYou must be at least $path&r!"
  no_path_exact: "&cYou must be at $path&r!"
  no_path_end: "&cYou must be ready to advance from $path&r!"
  light: "Light Level"
  time: "Time of Day"
  height: "Height"
  currency: "Currency"
