requirements:
  unknown: "&c禁止使用"
  property_requirement: "&r&c需要： &6$property &cof &4$value"
  property_max: "&r&c你的 &6$property &c已经溢出了！"
  property_min: "&r&c你的 &6$property &c必须大于&4$value"
  no_wand: "&c你必须手持一根法杖!"
  no_template: "&c你不能用$wand&c学习魔法。"
  no_path: "&c你不能在这里学习魔法。"
  no_class: "&c你必须先成为一名$class"
  no_required_path: "&c你必须至少达到$path&r!"
  no_path_exact: "&c你必须先成为$path&r!"
  no_path_end: "&c你必须先准备好成为$path&r!"
  light: "Light Level"
  time: "Time of Day"
  height: "Height"
  currency: "Currency"
